//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISAUTCON
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class EntitiesConsultas : DbContext
    {
        public EntitiesConsultas()
            : base("name=EntitiesConsultas")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<SP_BUSQUEDA_POR_NOMBRE_TOUCHSCREEN_Result> SP_BUSQUEDA_POR_NOMBRE_TOUCHSCREEN(string fANOMCONTR)
        {
            var fANOMCONTRParameter = fANOMCONTR != null ?
                new ObjectParameter("FANOMCONTR", fANOMCONTR) :
                new ObjectParameter("FANOMCONTR", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_BUSQUEDA_POR_NOMBRE_TOUCHSCREEN_Result>("SP_BUSQUEDA_POR_NOMBRE_TOUCHSCREEN", fANOMCONTRParameter);
        }
    
        public virtual ObjectResult<SP_BUSQUEDA_POR_NUMERO_DE_DOCUMENTO_TOUCHSCREEN_Result> SP_BUSQUEDA_POR_NUMERO_DE_DOCUMENTO_TOUCHSCREEN(string fANRODOCU)
        {
            var fANRODOCUParameter = fANRODOCU != null ?
                new ObjectParameter("FANRODOCU", fANRODOCU) :
                new ObjectParameter("FANRODOCU", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_BUSQUEDA_POR_NUMERO_DE_DOCUMENTO_TOUCHSCREEN_Result>("SP_BUSQUEDA_POR_NUMERO_DE_DOCUMENTO_TOUCHSCREEN", fANRODOCUParameter);
        }
    
        public virtual ObjectResult<SP_CONSULTA_CTATE_TO_TOUCHSCREEM_Result> SP_CONSULTA_CTATE_TO_TOUCHSCREEM(string fACODCONTR, string fACODTRIBU)
        {
            var fACODCONTRParameter = fACODCONTR != null ?
                new ObjectParameter("FACODCONTR", fACODCONTR) :
                new ObjectParameter("FACODCONTR", typeof(string));
    
            var fACODTRIBUParameter = fACODTRIBU != null ?
                new ObjectParameter("FACODTRIBU", fACODTRIBU) :
                new ObjectParameter("FACODTRIBU", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_CONSULTA_CTATE_TO_TOUCHSCREEM_Result>("SP_CONSULTA_CTATE_TO_TOUCHSCREEM", fACODCONTRParameter, fACODTRIBUParameter);
        }
    
        public virtual ObjectResult<string> SP_CONSULTA_REQTUPA(string fACODTRIBU, string fATIPOPERA, string fATIPCONTRIB)
        {
            var fACODTRIBUParameter = fACODTRIBU != null ?
                new ObjectParameter("FACODTRIBU", fACODTRIBU) :
                new ObjectParameter("FACODTRIBU", typeof(string));
    
            var fATIPOPERAParameter = fATIPOPERA != null ?
                new ObjectParameter("FATIPOPERA", fATIPOPERA) :
                new ObjectParameter("FATIPOPERA", typeof(string));
    
            var fATIPCONTRIBParameter = fATIPCONTRIB != null ?
                new ObjectParameter("FATIPCONTRIB", fATIPCONTRIB) :
                new ObjectParameter("FATIPCONTRIB", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("SP_CONSULTA_REQTUPA", fACODTRIBUParameter, fATIPOPERAParameter, fATIPCONTRIBParameter);
        }
    
        public virtual int SP_INSERTAR_RECIBO_PAGO_A_CUENTA_IP_RENTAS(string fAANOTRIBU, string fACODCONTR, string fAPERIODO, string fANRORECIB, Nullable<decimal> fNIMP01, Nullable<decimal> fngasadmin, Nullable<decimal> mONTO)
        {
            var fAANOTRIBUParameter = fAANOTRIBU != null ?
                new ObjectParameter("FAANOTRIBU", fAANOTRIBU) :
                new ObjectParameter("FAANOTRIBU", typeof(string));
    
            var fACODCONTRParameter = fACODCONTR != null ?
                new ObjectParameter("FACODCONTR", fACODCONTR) :
                new ObjectParameter("FACODCONTR", typeof(string));
    
            var fAPERIODOParameter = fAPERIODO != null ?
                new ObjectParameter("FAPERIODO", fAPERIODO) :
                new ObjectParameter("FAPERIODO", typeof(string));
    
            var fANRORECIBParameter = fANRORECIB != null ?
                new ObjectParameter("FANRORECIB", fANRORECIB) :
                new ObjectParameter("FANRORECIB", typeof(string));
    
            var fNIMP01Parameter = fNIMP01.HasValue ?
                new ObjectParameter("FNIMP01", fNIMP01) :
                new ObjectParameter("FNIMP01", typeof(decimal));
    
            var fngasadminParameter = fngasadmin.HasValue ?
                new ObjectParameter("fngasadmin", fngasadmin) :
                new ObjectParameter("fngasadmin", typeof(decimal));
    
            var mONTOParameter = mONTO.HasValue ?
                new ObjectParameter("MONTO", mONTO) :
                new ObjectParameter("MONTO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_INSERTAR_RECIBO_PAGO_A_CUENTA_IP_RENTAS", fAANOTRIBUParameter, fACODCONTRParameter, fAPERIODOParameter, fANRORECIBParameter, fNIMP01Parameter, fngasadminParameter, mONTOParameter);
        }
    
        public virtual int SP_PAGO_A_CUENTA_IP(string fACODCONTR, Nullable<decimal> mONTO)
        {
            var fACODCONTRParameter = fACODCONTR != null ?
                new ObjectParameter("FACODCONTR", fACODCONTR) :
                new ObjectParameter("FACODCONTR", typeof(string));
    
            var mONTOParameter = mONTO.HasValue ?
                new ObjectParameter("MONTO", mONTO) :
                new ObjectParameter("MONTO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_PAGO_A_CUENTA_IP", fACODCONTRParameter, mONTOParameter);
        }
    
        public virtual ObjectResult<SP_RECUPERAR_POR_CODIGO_TOUCHSCREEN_Result> SP_RECUPERAR_POR_CODIGO_TOUCHSCREEN(string fACODCONTR)
        {
            var fACODCONTRParameter = fACODCONTR != null ?
                new ObjectParameter("FACODCONTR", fACODCONTR) :
                new ObjectParameter("FACODCONTR", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_RECUPERAR_POR_CODIGO_TOUCHSCREEN_Result>("SP_RECUPERAR_POR_CODIGO_TOUCHSCREEN", fACODCONTRParameter);
        }
    }
}
