#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SISAUTCON
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ReportSever")]
	public partial class TributosedmxDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Definiciones de métodos de extensibilidad
    partial void OnCreated();
    #endregion
		
		public TributosedmxDataContext() : 
				base(global::SISAUTCON.Properties.Settings.Default.ReportSeverConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public TributosedmxDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TributosedmxDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TributosedmxDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public TributosedmxDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<REQTUPA> REQTUPA
		{
			get
			{
				return this.GetTable<REQTUPA>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.REQTUPA")]
	public partial class REQTUPA
	{
		
		private System.Nullable<int> _FNIDREQ;
		
		private string _FADESCRIPCION;
		
		private string _FACODTRIBU;
		
		private string _FATIPCONTRIB;
		
		private string _FATIPOPERA;
		
		private string _FADELETE;
		
		private string _FAOPERADOR;
		
		private System.Nullable<System.DateTime> _FDINGRESO;
		
		private System.Nullable<System.DateTime> _FDMODIFIC;
		
		public REQTUPA()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FNIDREQ", DbType="Int")]
		public System.Nullable<int> FNIDREQ
		{
			get
			{
				return this._FNIDREQ;
			}
			set
			{
				if ((this._FNIDREQ != value))
				{
					this._FNIDREQ = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FADESCRIPCION", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string FADESCRIPCION
		{
			get
			{
				return this._FADESCRIPCION;
			}
			set
			{
				if ((this._FADESCRIPCION != value))
				{
					this._FADESCRIPCION = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FACODTRIBU", DbType="VarChar(50)")]
		public string FACODTRIBU
		{
			get
			{
				return this._FACODTRIBU;
			}
			set
			{
				if ((this._FACODTRIBU != value))
				{
					this._FACODTRIBU = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FATIPCONTRIB", DbType="VarChar(50)")]
		public string FATIPCONTRIB
		{
			get
			{
				return this._FATIPCONTRIB;
			}
			set
			{
				if ((this._FATIPCONTRIB != value))
				{
					this._FATIPCONTRIB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FATIPOPERA", DbType="VarChar(20)")]
		public string FATIPOPERA
		{
			get
			{
				return this._FATIPOPERA;
			}
			set
			{
				if ((this._FATIPOPERA != value))
				{
					this._FATIPOPERA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FADELETE", DbType="VarChar(2)")]
		public string FADELETE
		{
			get
			{
				return this._FADELETE;
			}
			set
			{
				if ((this._FADELETE != value))
				{
					this._FADELETE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FAOPERADOR", DbType="VarChar(25)")]
		public string FAOPERADOR
		{
			get
			{
				return this._FAOPERADOR;
			}
			set
			{
				if ((this._FAOPERADOR != value))
				{
					this._FAOPERADOR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FDINGRESO", DbType="DateTime")]
		public System.Nullable<System.DateTime> FDINGRESO
		{
			get
			{
				return this._FDINGRESO;
			}
			set
			{
				if ((this._FDINGRESO != value))
				{
					this._FDINGRESO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FDMODIFIC", DbType="DateTime")]
		public System.Nullable<System.DateTime> FDMODIFIC
		{
			get
			{
				return this._FDMODIFIC;
			}
			set
			{
				if ((this._FDMODIFIC != value))
				{
					this._FDMODIFIC = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
